CREATE TABLE IF NOT EXISTS character_timeline
(
    snapshot_date                        Date,
    server_id                            LowCardinality(String),
    character_id                         FixedString(32),
    timeline_code                        UInt16,
    timeline_name                        LowCardinality(String),
    timeline_date                        DateTime,
    timeline_data_squad                  Nullable(UInt8),
    timeline_data_job_grow_id            Nullable(FixedString(32)),
    timeline_data_ticket                 LowCardinality(Nullable(String)),
    timeline_data_item_rarity            LowCardinality(Nullable(String)),
    timeline_data_item_name              Nullable(String),
    timeline_data_phase_name             LowCardinality(Nullable(String)),
    timeline_data_upgrade_name           LowCardinality(Nullable(String)),
    timeline_data_item_obtain_info       LowCardinality(Nullable(String)),
    timeline_data_matching               Nullable(UInt8),
    timeline_data_result_items           LowCardinality(Nullable(String)),
    timeline_data_level                  Nullable(UInt8),
    timeline_data_guide                  Nullable(UInt8),
    timeline_data_mist_gear              Nullable(UInt8),
    timeline_data_result                 Nullable(UInt8),
    timeline_data_hard                   Nullable(UInt8),
    timeline_data_point                  Nullable(UInt32),
    timeline_data_single                 Nullable(UInt8),
    timeline_data_before                 Nullable(UInt8),
    timeline_data_booster                Nullable(UInt8),
    timeline_data_after_name             Nullable(String),
    timeline_data_raid_name              LowCardinality(Nullable(String)),
    timeline_data_raid_party_name        Nullable(String),
    timeline_data_before_name            Nullable(String),
    timeline_data_refined_mist_gear      Nullable(UInt8),
    timeline_data_item_id                Nullable(FixedString(32)),
    timeline_data_channel_no             Nullable(UInt16),
    timeline_data_job_name               LowCardinality(Nullable(String)),
    timeline_data_amplification          Nullable(UInt8),
    timeline_data_channel_name           LowCardinality(Nullable(String)),
    timeline_data_adventure_safe_move_type LowCardinality(Nullable(String)),
    timeline_data_reinforce              Nullable(UInt8),
    timeline_data_pure_mist_gear         Nullable(UInt8),
    timeline_data_after                  Nullable(UInt8),
    timeline_data_npc_name               LowCardinality(Nullable(String)),
    timeline_data_mode                   LowCardinality(Nullable(String)),
    timeline_data_refine                 Nullable(UInt8),
    timeline_data_dungeon_name           LowCardinality(Nullable(String)),
    timeline_data_region_name            LowCardinality(Nullable(String)),
    timeline_data_safe                   Nullable(UInt8),
    timeline_data_job_id                 Nullable(FixedString(32)),
    timeline_data_mode_name              LowCardinality(Nullable(String)),
    timeline_data_job_grow_name          LowCardinality(Nullable(String)),
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(snapshot_date)
ORDER BY (snapshot_date, server_id, character_id, timeline_code, timeline_date)
SETTINGS index_granularity = 8192;
